apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: invalid-example
  tags:
    - test
spec:
  owner: group:default/platform
  type: service
  parameters:
    - title: Component
      required:
        - componentId
      properties:
        componentId:
          title: Component ID
          type: string
  steps:
    - id: create
      action: debug:log
      input:
        message: ${{ parameters.componentId }}
    - id: finish
      action: debug:log
      input:
        message: done
