apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: repair-me
  title: Repair Me
  description: Template with fixable gotchas
  tags:
    - test
spec:
  owner: group:default/platform-team
  type: service
  parameters:
    - title: Details
      properties:
        name:
          title: Name
          type: string
  steps:
    - id: pub
      action: publish:github
      input: {}
