apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: invalid-example
  tags:
    - test
spec:
  owner: group:default/platform
  type: service
  parameters: []
  steps:
    - id: create
      action: debug:log
      input:
        message: ${{ parameters.componentId }}
    - id: create
      action: debug:log
      input:
        message: done
